[package]
name = "must"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vte = { version = "0.13.0" }
ggez = { version = "0.9.3" }
telnet = { version = "0.2.1" }
